export const INPUT_EMPTY = 'INPUT_EMPTY';
export const NOT_LOGIN = 'NOT_LOGIN';
export const NET_OFFLINE = 'NET_OFFLINE';
export const SERVICE_NOT_RESPONDING = 'SERVICE_NOT_RESPONDING';
export const QUESTION_FETCH_MAX = 'QUESTION_FETCH_MAX';
export const INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
export const WS_ERROR = 'WS_ERROR';
